.\" Copyright (c) 2003-2008 Maik Broemme <mbroemme@plusserver.de>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.TH libmpq 3 2008-04-01 "The MoPaQ archive library"
.SH NAME
libmpq \- cross-platform C library for manipulating mpq archives.
.SH SYNOPSIS
.nf
.B
#include <mpq.h>
.sp
.BI "int32_t libmpq__init();"
.fi
.SH DESCRIPTION
.PP
Call \fBlibmpq__init\fP() to initialize libmpq. You have to call this function in order to be able to use the rest of the libmpq API. For each time you call \fBlibmpq__init\fP() you have to call \fBlibmpq__shutdown\fP() later in order properly shut down the library.
.LP
The \fBlibmpq__init\fP() function takes no arguments.
.SH RETURN VALUE
On success, \fBlibmpq__init\fP() returns LIBMPQ_SUCCESS. Otherwise one of the following constants is returned.
.TP
.B LIBMPQ_ERROR_DECRYPT
The decryption buffer could not be set up.
.SH SEE ALSO
.BR libmpq__shutdown(3)
.SH AUTHOR
Check documentation.
.TP
libmpq is (c) 2003-2008
.B Maik Broemme <mbroemme@plusserver.de>
.PP
The above e-mail address can be used to send bug reports, feedbacks or library enhancements.
